In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
pd.__version__

'1.4.4'

In [3]:
#pip install openpyxl

In [3]:
df=pd.read_excel('homeprices.xlsx')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
type(df[['area']])

pandas.core.frame.DataFrame

In [5]:
model=linear_model.LinearRegression()
model.fit(df[['area']], df[['price']])

LinearRegression()

In [6]:
model.coef_

array([[135.78767123]])

In [7]:
model.intercept_

array([180616.43835616])

In [8]:
model.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[859554.79452055]])

# Save Model To a File Using Python Pickle

In [9]:
import pickle

In [10]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

# Save Model To a File Using Python Joblib

In [11]:
import joblib as jbl

jbl.dump(model,'My_JobModel')

['My_JobModel']

# Load Saved Model

In [12]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [13]:
mp.coef_

array([[135.78767123]])

In [14]:
mp.intercept_

array([180616.43835616])

In [15]:
mp.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[859554.79452055]])